# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ main ]

jobs:
  FTP-Deploy-Action:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
      - uses: actions/checkout@master
        with:
          fetch-depth: 2
      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          ftp-server: ${{ secrets.HOST }}
          ftp-username: ${{ secrets.USERNAME }}
          ftp-password: ${{ secrets.PASSWORD }}
          git-ftp-args: --insecure
